USE master;

DROP DATABASE DB3;

CREATE DATABASE DB3;

USE DB3;     
CREATE TABLE TBL_COD_PROD(
ID INT IDENTITY(1,1),
NOME VARCHAR(15),
PRECO MONEY,
NONE NVARCHAR(100) NOT NULL
PRIMARY KEY (ID),
);

CREATE TABLE TBL_VDA(
ID INT IDENTITY(1,1),
DATA DATE,
VALOR MONEY,
ID_L INT,
PRIMARY KEY (ID),
);

CREATE TABLE TBL_CLIENTE(
ID INT IDENTITY(1,1),
NOME VARCHAR(15),
NONE NVARCHAR(100) NOT NULL
PRIMARY KEY (ID),
);

CREATE TABLE TBL_PROD_VENDIDO(
ID INT IDENTITY(1,1),
ID_VDA INT,
ID_PROD INT,
QUANTIDADE DECIMAL (3,2),
PRIMARY KEY (ID),
);

GO

ALTER TABLE TBL_PROD_VENDIDO
ADD CONSTRAINT FK_VDA_PROD_VENDIDO
FOREIGN KEY (ID_VDA) REFERENCES TBL_VDA(ID);

ALTER TABLE TBL_PROD_VENDIDO
ADD CONSTRAINT FK_COD_PROD_VENDIDO
FOREIGN KEY (ID_PROD) REFERENCES TBL_COD_PROD(ID);

ALTER TABLE TBL_VDA
ADD CONSTRAINT FK_TBL_VDA
FOREIGN KEY (ID_L) REFERENCES TBL_CLIENTE(ID);
